//! Allocation witness: prove that the static-pool [`ChannelFactory`]
//! generated by [`define_static_channels!`] does not invoke the global
//! allocator on the request/response hot path.
//!
//! [`ChannelFactory`]: simple_someip::transport::ChannelFactory
//! [`define_static_channels!`]: simple_someip::define_static_channels
//!
//! # What this test asserts
//!
//! 1. `Client::new_with_deps` is allowed to allocate — the std-flavored
//!    `Arc<Mutex<E2ERegistry>>` and `Arc<RwLock<Ipv4Addr>>` handles
//!    used here, plus tokio's task-spawning machinery, all heap-back.
//!    The strategic-goal claim is "zero heap **after** `Client::new`
//!    returns," not "zero heap, period."
//! 2. After construction, calling [`Client::interface`] (a pure handle
//!    read) does not allocate.
//! 3. After construction, claiming + dropping a oneshot through the
//!    macro-declared static pool does not allocate. This is the
//!    direct witness for the strategic-goal claim about per-call
//!    channel storage.
//!
//! # Why a counting allocator and not a panicking one
//!
//! The design specifies a `#[global_allocator]` shim that **panics**
//! on allocation after `Client::new` returns. That requires a no-alloc
//! test executor (tokio's runtime allocates on its own), no-alloc
//! `Spawner` impl for the per-socket loops, and stack-based
//! `E2ERegistryHandle` / `InterfaceHandle` impls. Each of those is a
//! real piece of work and lives under the CI harness umbrella.
//!
//! The counting allocator here is a softer witness: it instruments
//! every allocation through a [`std::sync::atomic::AtomicUsize`]
//! counter and checks the delta across specific operations. It
//! catches regressions where a channel construction starts heap-
//! allocating; it does not catch "tokio runtime allocated to drive
//! a sleep" because that allocation is acceptable in the host-test
//! context. The panicking harness will catch both.
#![cfg(all(feature = "client", feature = "bare_metal"))]

use core::future::Future;
use core::net::{Ipv4Addr, SocketAddrV4};
use core::pin::Pin;
use core::task::{Context, Poll};
use core::time::Duration;
use std::alloc::{GlobalAlloc, Layout, System};
use std::collections::VecDeque;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};

use simple_someip::client::Error as ClientError;
use simple_someip::client::{ClientUpdate, ControlMessage, ReceivedMessage, SendMessage};
use simple_someip::define_static_channels;
use simple_someip::e2e::E2ERegistry;
use simple_someip::protocol::sd::RebootFlag;
use simple_someip::transport::{
    ChannelFactory, OneshotSend, ReceivedDatagram, SocketOptions, Spawner, Timer, TransportError,
    TransportFactory, TransportSocket,
};
use simple_someip::{Client, ClientDeps, RawPayload};

// ── Counting global allocator ─────────────────────────────────────────

static ALLOC_COUNT: AtomicUsize = AtomicUsize::new(0);

/// Serializes the alloc-measurement region across `#[tokio::test]`s in
/// this file. Without it, parallel test execution would interleave
/// allocations from one test into another's `(baseline, end)` window.
static MEASURE_LOCK: Mutex<()> = Mutex::new(());

struct CountingAllocator;

unsafe impl GlobalAlloc for CountingAllocator {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        ALLOC_COUNT.fetch_add(1, Ordering::Relaxed);
        // SAFETY: forwarding to System with caller's layout
        // contract preserved.
        unsafe { System.alloc(layout) }
    }
    unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
        // SAFETY: forwarding to System; ptr/layout came from System::alloc
        // (we only delegate forward).
        unsafe { System.dealloc(ptr, layout) }
    }
    unsafe fn alloc_zeroed(&self, layout: Layout) -> *mut u8 {
        ALLOC_COUNT.fetch_add(1, Ordering::Relaxed);
        // SAFETY: forwarding to System.
        unsafe { System.alloc_zeroed(layout) }
    }
    unsafe fn realloc(&self, ptr: *mut u8, layout: Layout, new_size: usize) -> *mut u8 {
        ALLOC_COUNT.fetch_add(1, Ordering::Relaxed);
        // SAFETY: forwarding to System; ptr/layout/new_size invariants
        // upheld by caller.
        unsafe { System.realloc(ptr, layout, new_size) }
    }
}

#[global_allocator]
static GLOBAL: CountingAllocator = CountingAllocator;

fn alloc_count() -> usize {
    ALLOC_COUNT.load(Ordering::Relaxed)
}

// ── Static channels declaration ───────────────────────────────────────

define_static_channels! {
    name: WitnessChannels,
    oneshot: [
        (Result<(), ClientError>, 8),
        (Result<RawPayload, ClientError>, 4),
        (Result<RebootFlag, ClientError>, 4),
    ],
    bounded: [
        ((ControlMessage<RawPayload, WitnessChannels>, 4), 1),
        ((SendMessage<RawPayload, WitnessChannels>, 16), 4),
        ((Result<ReceivedMessage<RawPayload>, ClientError>, 16), 4),
    ],
    unbounded: [
        (ClientUpdate<RawPayload>, 1),
    ],
}

// ── Mock transport (mirrors tests/bare_metal_client.rs) ───────────────

#[derive(Default)]
struct MockPipe {
    sent: Mutex<VecDeque<(Vec<u8>, SocketAddrV4)>>,
    inbound: Mutex<VecDeque<(Vec<u8>, SocketAddrV4)>>,
    inbound_waker: Mutex<Option<core::task::Waker>>,
}


#[derive(Clone)]
struct MockFactory {
    pipe: Arc<MockPipe>,
    local_port: Arc<Mutex<u16>>,
}

impl TransportFactory for MockFactory {
    type Socket = MockSocket;
    fn bind(
        &self,
        addr: SocketAddrV4,
        _options: &SocketOptions,
    ) -> impl Future<Output = Result<Self::Socket, TransportError>> + Send {
        let pipe = Arc::clone(&self.pipe);
        let mut p = self.local_port.lock().unwrap();
        let port = if addr.port() == 0 {
            let next = *p + 1;
            *p = next;
            30000 + next
        } else {
            addr.port()
        };
        let local = SocketAddrV4::new(*addr.ip(), port);
        async move { Ok(MockSocket { pipe, local }) }
    }
}

struct MockSocket {
    pipe: Arc<MockPipe>,
    local: SocketAddrV4,
}

struct MockSendFut {
    pipe: Arc<MockPipe>,
    bytes: Option<Vec<u8>>,
    target: SocketAddrV4,
}

impl Future for MockSendFut {
    type Output = Result<(), TransportError>;
    fn poll(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Self::Output> {
        let me = self.get_mut();
        if let Some(bytes) = me.bytes.take() {
            me.pipe.sent.lock().unwrap().push_back((bytes, me.target));
        }
        Poll::Ready(Ok(()))
    }
}

struct MockRecvFut<'a> {
    pipe: Arc<MockPipe>,
    buf: &'a mut [u8],
}

impl Future for MockRecvFut<'_> {
    type Output = Result<ReceivedDatagram, TransportError>;
    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        let me = self.get_mut();
        let entry = me.pipe.inbound.lock().unwrap().pop_front();
        match entry {
            Some((bytes, source)) => {
                let n = bytes.len().min(me.buf.len());
                me.buf[..n].copy_from_slice(&bytes[..n]);
                Poll::Ready(Ok(ReceivedDatagram {
                    bytes_received: n,
                    source,
                    truncated: n < bytes.len(),
                }))
            }
            None => {
                *me.pipe.inbound_waker.lock().unwrap() = Some(cx.waker().clone());
                if let Some((bytes, source)) = me.pipe.inbound.lock().unwrap().pop_front() {
                    let n = bytes.len().min(me.buf.len());
                    me.buf[..n].copy_from_slice(&bytes[..n]);
                    return Poll::Ready(Ok(ReceivedDatagram {
                        bytes_received: n,
                        source,
                        truncated: n < bytes.len(),
                    }));
                }
                Poll::Pending
            }
        }
    }
}

impl TransportSocket for MockSocket {
    type SendFuture<'a> = MockSendFut;
    type RecvFuture<'a> = MockRecvFut<'a>;

    fn send_to<'a>(&'a self, buf: &'a [u8], target: SocketAddrV4) -> Self::SendFuture<'a> {
        MockSendFut {
            pipe: Arc::clone(&self.pipe),
            bytes: Some(buf.to_vec()),
            target,
        }
    }

    fn recv_from<'a>(&'a self, buf: &'a mut [u8]) -> Self::RecvFuture<'a> {
        MockRecvFut {
            pipe: Arc::clone(&self.pipe),
            buf,
        }
    }

    fn local_addr(&self) -> Result<SocketAddrV4, TransportError> {
        Ok(self.local)
    }

    fn join_multicast_v4(&self, _g: Ipv4Addr, _i: Ipv4Addr) -> Result<(), TransportError> {
        Ok(())
    }
    fn leave_multicast_v4(&self, _g: Ipv4Addr, _i: Ipv4Addr) -> Result<(), TransportError> {
        Ok(())
    }
}

struct MockTimer;
impl Timer for MockTimer {
    async fn sleep(&self, duration: Duration) {
        tokio::time::sleep(duration).await;
    }
}

struct TokioBackedSpawner;
impl Spawner for TokioBackedSpawner {
    fn spawn(&self, future: impl Future<Output = ()> + Send + 'static) {
        drop(tokio::spawn(future));
    }
}

// ── Witnesses ─────────────────────────────────────────────────────────

#[tokio::test]
async fn no_alloc_when_claiming_oneshot_through_static_pool() {
    let _guard = MEASURE_LOCK.lock().unwrap();
    // Warm any one-time tokio-runtime / first-claim seeding allocations
    // before measuring.
    {
        let (tx, _rx) = WitnessChannels::oneshot::<Result<(), ClientError>>();
        tx.send(Ok(())).unwrap();
    }

    let baseline = alloc_count();
    {
        // A second claim/release cycle must not allocate. The pool is
        // already seeded; the slot returned from the first claim is on
        // the free list.
        let (tx, _rx) = WitnessChannels::oneshot::<Result<(), ClientError>>();
        tx.send(Ok(())).unwrap();
    }
    let delta = alloc_count() - baseline;
    assert_eq!(
        delta, 0,
        "static-pool oneshot claim/release allocated {delta} times \
         after warm-up; expected zero",
    );
}

#[tokio::test]
async fn client_interface_read_after_construction_does_not_allocate() {
    let pipe = Arc::new(MockPipe::default());
    let factory = MockFactory {
        pipe: Arc::clone(&pipe),
        local_port: Arc::new(Mutex::new(0)),
    };
    let interface_handle: Arc<std::sync::RwLock<Ipv4Addr>> =
        Arc::new(std::sync::RwLock::new(Ipv4Addr::LOCALHOST));
    let e2e_handle: Arc<Mutex<E2ERegistry>> = Arc::new(Mutex::new(E2ERegistry::new()));

    let (client, _updates, run_fut) = Client::<
        RawPayload,
        Arc<Mutex<E2ERegistry>>,
        Arc<std::sync::RwLock<Ipv4Addr>>,
        WitnessChannels,
    >::new_with_deps(
        ClientDeps {
            factory,
            spawner: TokioBackedSpawner,
            timer: MockTimer,
            e2e_registry: e2e_handle,
            interface: interface_handle,
        },
        false,
    );
    let run_handle = tokio::spawn(run_fut);

    // After construction (and after a yield to give the spawn loop a
    // chance to do its one-time setup allocs), measure pure-handle
    // operations under the serialization lock.
    tokio::task::yield_now().await;
    let _guard = MEASURE_LOCK.lock().unwrap();
    let baseline = alloc_count();
    for _ in 0..16 {
        assert_eq!(client.interface(), Ipv4Addr::LOCALHOST);
    }
    let delta = alloc_count() - baseline;
    assert_eq!(
        delta, 0,
        "Client::interface() x16 allocated {delta} times; expected zero",
    );

    run_handle.abort();
    drop(client);
}
