cmake_minimum_required(VERSION 3.13)
project(vsomeip_peer CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(vsomeip3 REQUIRED)
find_package(Threads REQUIRED)
add_executable(peer peer.cpp)
target_link_libraries(peer PRIVATE vsomeip3 Threads::Threads)
target_include_directories(peer PRIVATE ${VSOMEIP_INCLUDE_DIRS})
